/* ============================================================
   大梅沙垃圾图鉴 · Preset Specimen Data
   24 items, one per image in assets/hero-trash/
   ============================================================ */

window.TRASH_CATEGORIES = [
  '全部', '塑料制品', '金属异物', '日用生活', '食品包装', '玩具残骸', '神秘物品'
];

window.PRESET_DATA = [
  {
    id: 'DMS-001',
    name: '瑞士漂来的健康说明书',
    latinName: 'Involucrum helveticum probioti',
    category: '食品包装',
    discoveredAt: '大梅沙海滨公园沙滩',
    coordinates: '22°36\'08"N 114°18\'45"E',
    date: '2026-03-02',
    foundBy: '志愿者小雯',
    photoUrl: 'assets/hero-trash/Swiss益生菌包装.png',
    description: '一枚来自瑞士品牌的益生菌包装袋，在大梅沙海滩用身体力行地证明：健康食品的消费者，并不一定是对环境健康最上心的人。包装袋正面印着"守护肠道生态"，背面则躺在沙滩上守护着沙粒。本所认为，这是今年度最具讽刺意味的食品包装标本之一，建议纳入健康教育教材。',
    weirdness: 7,
    frequency: 3,
    weight: 1,
    dangerLevel: 1,
    isPreset: true
  },
  {
    id: 'DMS-002',
    name: '双手离去后的空皮囊',
    latinName: 'Chirotheca vacua phantasma',
    category: '塑料制品',
    discoveredAt: '大梅沙海滨公园沙滩',
    coordinates: '22°36\'11"N 114°18\'48"E',
    date: '2026-01-18',
    foundBy: '志愿者阿强',
    photoUrl: 'assets/hero-trash/一次性手套包装袋.png',
    description: '一次性手套的包装袋，手套本人早已不知所踪，只剩下一个薄薄的透明外壳躺在沙滩上发呆。本所对此标本的哲学意涵进行了深入探讨：它究竟是手的幽灵，还是防护意识的空壳？讨论持续了十七分钟，最终以"反正都是垃圾"收场。',
    weirdness: 5,
    frequency: 6,
    weight: 1,
    dangerLevel: 1,
    isPreset: true
  },
  {
    id: 'DMS-003',
    name: '万能鉴定所拒绝鉴定的物品',
    latinName: 'Res ignota categoriae nullius',
    category: '神秘物品',
    discoveredAt: '大梅沙海滨公园沙滩',
    coordinates: '22°36\'19"N 114°18\'56"E',
    date: '2025-11-04',
    foundBy: '队长老李',
    photoUrl: 'assets/hero-trash/不明物品.png',
    description: '一件连本所专家团队都无法准确归类的神秘物品。历经材质分析、来源推测、气味鉴别三轮讨论，最终一致同意：它就是个不明物品。本所决定为它专门新建档案分类，并在内部备注"不要问，问就是不知道"。这是本季度最令人智识受挫的标本，荣获"最欠解释奖"。',
    weirdness: 10,
    frequency: 1,
    weight: 4,
    dangerLevel: 2,
    isPreset: true
  },
  {
    id: 'DMS-004',
    name: '礁石上的小传教士',
    latinName: 'Crux plastica evangelica',
    category: '神秘物品',
    discoveredAt: '大梅沙海滨公园沙滩',
    coordinates: '22°36\'16"N 114°18\'53"E',
    date: '2025-12-25',
    foundBy: '志愿者小美',
    photoUrl: 'assets/hero-trash/十字架.png',
    description: '一枚小巧的十字架饰品，静静地躺在礁石缝隙中，仿佛在等待什么。本所成员一致认为，在圣诞节当天发现这枚十字架具有相当的戏剧性。它来自项链？护身符？还是某个一时冲动的仪式？我们不得而知。唯一确定的是，它的信仰与主人之间，已经隔着一片大海。',
    weirdness: 8,
    frequency: 2,
    weight: 1,
    dangerLevel: 1,
    isPreset: true
  },
  {
    id: 'DMS-005',
    name: '酥脆记忆的终点站',
    latinName: 'Fragmen nucis abandonatum',
    category: '食品包装',
    discoveredAt: '大梅沙海滨公园沙滩',
    coordinates: '22°36\'07"N 114°18\'44"E',
    date: '2026-02-14',
    foundBy: '志愿者小张',
    photoUrl: 'assets/hero-trash/坚果酥.png',
    description: '一袋坚果酥的包装袋，残留有细碎的酥饼粉末，说明最后一粒也没有被浪费——只是包装袋本身被浪费了。本所计算，如果坚果酥的美味指数与其包装袋对环境的影响成正比，那它的综合得分将会是个相当复杂的算术题。发现于情人节当天，本所认为这不是巧合。',
    weirdness: 4,
    frequency: 7,
    weight: 1,
    dangerLevel: 1,
    isPreset: true
  },
  {
    id: 'DMS-006',
    name: '本地户口的流浪儿',
    latinName: 'Saccus papyri domesticus errans',
    category: '日用生活',
    discoveredAt: '大梅沙海滨公园沙滩',
    coordinates: '22°36\'09"N 114°18\'46"E',
    date: '2026-04-05',
    foundBy: '志愿者阿明',
    photoUrl: 'assets/hero-trash/大梅沙海滨公园纸袋.png',
    description: '大梅沙海滨公园自己的纸袋，流落在大梅沙海滨公园的沙滩上。本所为此感到一种奇异的哲学困惑：它回家了吗？还是恰恰相反？这是本所迄今为止遇到的身份最明确却处境最尴尬的标本——印着"大梅沙"的袋子成了大梅沙的垃圾，此乃循环之大讽刺。已被本所列为年度最具本地特色标本。',
    weirdness: 9,
    frequency: 3,
    weight: 1,
    dangerLevel: 1,
    isPreset: true
  },
  {
    id: 'DMS-007',
    name: '六千六百万年后再次搁浅',
    latinName: 'Dinosaurus plasticae temporis perditi',
    category: '玩具残骸',
    discoveredAt: '大梅沙海滨公园沙滩',
    coordinates: '22°36\'13"N 114°18\'51"E',
    date: '2025-08-15',
    foundBy: '志愿者小陈',
    photoUrl: 'assets/hero-trash/恐龙.png',
    description: '一只塑料恐龙玩具，姿态依然威武，眼神依然凶猛，只是已经离开了六千六百万年前的生态位，也离开了某个孩子的手心。本所注意到，它的塑料配方大约需要四百年才能降解，这意味着它将比任何人类文明都活得更久。这只恐龙，才是真正的物种顽强者。',
    weirdness: 7,
    frequency: 4,
    weight: 3,
    dangerLevel: 1,
    isPreset: true
  },
  {
    id: 'DMS-008',
    name: '碎裂的数字世界观',
    latinName: 'Retina digitalis fracta marinae',
    category: '神秘物品',
    discoveredAt: '大梅沙海滨公园沙滩',
    coordinates: '22°36\'17"N 114°18\'54"E',
    date: '2026-01-30',
    foundBy: '志愿者小欣',
    photoUrl: 'assets/hero-trash/手机屏幕.png',
    description: '一块破碎的手机屏幕，裂纹蛛网状扩散，像一幅抽象画。屏幕已黑，内存的秘密已随主人而去。本所对其来源进行了合理推测：失手摔入海、愤怒扔入浪、遭遇意外损坏后被随意丢弃——三种可能性均指向某个值得回味的故事。我们决定不知道那个故事，因为想象空间更大。',
    weirdness: 8,
    frequency: 2,
    weight: 5,
    dangerLevel: 3,
    isPreset: true
  },
  {
    id: 'DMS-009',
    name: '未竟沙堡工程的独苗遗孤',
    latinName: 'Pala arenaria projecti incompletis',
    category: '玩具残骸',
    discoveredAt: '大梅沙海滨公园沙滩',
    coordinates: '22°36\'06"N 114°18\'43"E',
    date: '2025-07-20',
    foundBy: '志愿者小雯',
    photoUrl: 'assets/hero-trash/推沙铲.png',
    description: '一把儿童推沙铲，颜色鲜艳，铲口依然完好，具备充分的工作能力。然而它的主人却已不在，留下它独自面对尚未完工的沙堡。本所推断，这场撤退发生得相当突然——可能是冰淇淋来了，可能是妈妈喊回家了，也可能是涨潮了。无论如何，铲子留下了，梦想也留下了。',
    weirdness: 5,
    frequency: 5,
    weight: 2,
    dangerLevel: 1,
    isPreset: true
  },
  {
    id: 'DMS-010',
    name: '旺仔牌流浪指南（空版）',
    latinName: 'Tubus wangzai itinerarium vacuus',
    category: '食品包装',
    discoveredAt: '大梅沙海滨公园沙滩',
    coordinates: '22°36\'10"N 114°18\'47"E',
    date: '2026-03-22',
    foundBy: '志愿者阿强',
    photoUrl: 'assets/hero-trash/旺旺.png',
    description: '旺仔牌软管包装，已彻底挤空，尾部整齐卷起，一丝奶味不剩。这份对产品的彻底热情令本所动容——可惜热情只延续到最后一滴，而非一直到垃圾桶。本所估计，大梅沙海滩上的旺仔包装袋如果首尾相连，足以绘制一幅旺旺集团的贸易地图。',
    weirdness: 3,
    frequency: 9,
    weight: 1,
    dangerLevel: 1,
    isPreset: true
  },
  {
    id: 'DMS-011',
    name: '搅动过海风与美食的木质旅行者',
    latinName: 'Cochleare ligneum vagabundi marinae',
    category: '日用生活',
    discoveredAt: '大梅沙海滨公园沙滩',
    coordinates: '22°36\'12"N 114°18\'49"E',
    date: '2025-09-08',
    foundBy: '队长老李',
    photoUrl: 'assets/hero-trash/木勺.png',
    description: '一把原木色木勺，理论上是环保餐具的正确选择。然而它此刻正以一种极具讽刺意味的姿态躺在沙滩上，用实际行动宣告：环保餐具只有被妥善处置，才称得上是环保。本所决定将这把木勺作为户外餐具使用规范的反面教材，并为它写下墓志铭："它做对了七件事，却在第八件上功亏一篑。"',
    weirdness: 5,
    frequency: 6,
    weight: 2,
    dangerLevel: 1,
    isPreset: true
  },
  {
    id: 'DMS-012',
    name: '蛋白质的最后一次露营',
    latinName: 'Involucrum salsicia campestris ultimum',
    category: '食品包装',
    discoveredAt: '大梅沙海滨公园沙滩',
    coordinates: '22°36\'05"N 114°18\'42"E',
    date: '2026-02-28',
    foundBy: '志愿者小张',
    photoUrl: 'assets/hero-trash/火腿肠.png',
    description: '一根火腿肠的外包装，肠衣已被整齐剥开，可见享用过程颇为从容。火腿肠作为中国户外活动的国民零食，其包装袋在各大景区、海滩的出镜率居高不下。本所统计，仅大梅沙海滩每年回收的火腿肠包装即可估算出该区域游客的蛋白质摄入偏好——数据相当可观，且持续上升。',
    weirdness: 3,
    frequency: 10,
    weight: 1,
    dangerLevel: 1,
    isPreset: true
  },
  {
    id: 'DMS-013',
    name: '以为自己是宝贝的圆形异物',
    latinName: 'Sphaera margarita artificialis',
    category: '神秘物品',
    discoveredAt: '大梅沙海滨公园沙滩',
    coordinates: '22°36\'15"N 114°18\'52"E',
    date: '2025-10-31',
    foundBy: '志愿者小美',
    photoUrl: 'assets/hero-trash/珍珠.png',
    description: '一颗疑似仿珍珠的圆形小球，光泽度约有真珍珠的三成，自信心则有真珍珠的十二成。本所成员中有人主张将其当作装饰品带走，被队长严正阻止，理由是"这是标本，不是纪念品"。该球目前仍在档案室中接受身份甄别，预计鉴定结果为：人造，廉价，但充满个性。',
    weirdness: 8,
    frequency: 2,
    weight: 1,
    dangerLevel: 1,
    isPreset: true
  },
  {
    id: 'DMS-014',
    name: '失去主体的孤独守门员',
    latinName: 'Operculum plasticum solitarium',
    category: '塑料制品',
    discoveredAt: '大梅沙海滨公园沙滩',
    coordinates: '22°36\'14"N 114°18\'51"E',
    date: '2026-04-12',
    foundBy: '志愿者阿明',
    photoUrl: 'assets/hero-trash/瓶盖.png',
    description: '一枚蓝色塑料大瓶盖，脱离本体已久，独自在高潮线以上的干沙区坚守岗位。它的瓶子在哪里？本所无从得知。每一枚孤独的瓶盖背后，都是一个完整瓶子的失踪故事。统计数据表明，瓶盖是中国海滩上回收率最低的塑料制品之一，因为它们太轻，风一吹就不见了，但不会真的消失。',
    weirdness: 2,
    frequency: 10,
    weight: 1,
    dangerLevel: 2,
    isPreset: true
  },
  {
    id: 'DMS-015',
    name: '百亿活菌的透明空城计',
    latinName: 'Ampulla yakult vacuus probioti',
    category: '塑料制品',
    discoveredAt: '大梅沙海滨公园沙滩',
    coordinates: '22°36\'08"N 114°18\'45"E',
    date: '2025-11-20',
    foundBy: '志愿者小陈',
    photoUrl: 'assets/hero-trash/益力多瓶子.png',
    description: '一只益力多小瓶，容量65毫升，曾经住着一百亿个活性乳酸菌。如今菌们已随主人而去，只剩下晶莹的外壳孤零零地立在沙滩上。本所对这只瓶子充满敬意：它用最小的体积，容纳了最多的生命，完成了使命后，却以一种不那么光荣的方式画上了句号。真是个两极分化的标本。',
    weirdness: 4,
    frequency: 8,
    weight: 1,
    dangerLevel: 1,
    isPreset: true
  },
  {
    id: 'DMS-016',
    name: '搁浅的世界观',
    latinName: 'Spectacula abandoniensis marinae',
    category: '日用生活',
    discoveredAt: '大梅沙海滨公园沙滩',
    coordinates: '22°36\'18"N 114°18\'55"E',
    date: '2026-03-15',
    foundBy: '志愿者小欣',
    photoUrl: 'assets/hero-trash/眼镜.png',
    description: '一副眼镜，镜片尚在，镜腿齐全，只是主人不见了。通过镜片的折射率，本所推测失主视力约在四百度左右，这意味着失去眼镜后，他看到的大梅沙是一片美丽的模糊。本所对失主的处境深感同情，同时也对他在没有眼镜的情况下如何找到回家的路感到好奇。',
    weirdness: 7,
    frequency: 3,
    weight: 4,
    dangerLevel: 1,
    isPreset: true
  },
  {
    id: 'DMS-017',
    name: '紫色哲学家的身份困惑',
    latinName: 'Hippocampus violacea philosophus',
    category: '玩具残骸',
    discoveredAt: '大梅沙海滨公园沙滩',
    coordinates: '22°36\'14"N 114°18\'50"E',
    date: '2025-08-03',
    foundBy: '志愿者阿强',
    photoUrl: 'assets/hero-trash/紫色海马.png',
    description: '紫色硬质塑料海马玩具，约十厘米高，表情呈现出一种超然的淡定。本所认为，一件海马造型的玩具出现在真实的海边，具有相当的哲学意味——它究竟算是回家了，还是迷路了？它代表的是海洋，还是人类对海洋的拙劣模仿？本所讨论了二十分钟，无果而终，将其列为本季度最具文学价值的标本。',
    weirdness: 8,
    frequency: 2,
    weight: 1,
    dangerLevel: 1,
    isPreset: true
  },
  {
    id: 'DMS-018',
    name: '激情燃尽后的独行侠',
    latinName: 'Cochleare rubrum passionis derelictum',
    category: '日用生活',
    discoveredAt: '大梅沙海滨公园沙滩',
    coordinates: '22°36\'10"N 114°18\'47"E',
    date: '2025-12-08',
    foundBy: '志愿者小雯',
    photoUrl: 'assets/hero-trash/红色勺子.png',
    description: '一把红色塑料勺，颜色鲜艳如初，勺面干净，没有任何食物残留——它究竟搅拌过什么，本所已无从考证。红色，是激情的颜色，也是最常见的一次性餐具颜色。本所注意到，它的红与这片蓝色的海形成了强烈的视觉对比，大自然以一贯的审美品位，拒绝这把勺子的存在。',
    weirdness: 4,
    frequency: 7,
    weight: 1,
    dangerLevel: 1,
    isPreset: true
  },
  {
    id: 'DMS-019',
    name: '环保梦想家的讽刺现身',
    latinName: 'Balaena viridis plasticae ironica',
    category: '玩具残骸',
    discoveredAt: '大梅沙海滨公园沙滩',
    coordinates: '22°36\'11"N 114°18\'48"E',
    date: '2025-07-05',
    foundBy: '志愿者小美',
    photoUrl: 'assets/hero-trash/绿色鲸鱼.png',
    description: '一只绿色塑料鲸鱼玩具，体型精巧，造型可爱，正以一种极具讽刺性的姿态出现在真实的海边。绿色，通常象征环保。鲸鱼，是海洋污染最著名的受害者之一。一只绿色塑料鲸鱼躺在被塑料污染的沙滩上，本所认为此标本足以作为环境教育课程的封面，无需任何额外说明。',
    weirdness: 9,
    frequency: 3,
    weight: 2,
    dangerLevel: 2,
    isPreset: true
  },
  {
    id: 'DMS-020',
    name: '回家了但又没完全回家',
    latinName: 'Piscis caeruleus plasticae paradoxus',
    category: '玩具残骸',
    discoveredAt: '大梅沙海滨公园沙滩',
    coordinates: '22°36\'06"N 114°18\'43"E',
    date: '2026-01-07',
    foundBy: '志愿者小张',
    photoUrl: 'assets/hero-trash/蓝色小鱼.png',
    description: '一条蓝色塑料小鱼玩具，出现在海边，这在逻辑上可以理解为"回家"，在现实中却是一场误会。它的家在某个孩子的浴室或浴缸里，而不是真正的大海。本所对这条鱼的处境深感同情，它带着"鱼"的外形，却承担着"垃圾"的命运，蓝色的身体，与蓝色的海水构成了一种残酷的近似。',
    weirdness: 7,
    frequency: 5,
    weight: 1,
    dangerLevel: 1,
    isPreset: true
  },
  {
    id: 'DMS-021',
    name: '原住民的意外归档',
    latinName: 'Concha marina incerta archivi',
    category: '神秘物品',
    discoveredAt: '大梅沙海滨公园沙滩',
    coordinates: '22°36\'20"N 114°18\'57"E',
    date: '2025-09-21',
    foundBy: '队长老李',
    photoUrl: 'assets/hero-trash/贝壳.png',
    description: '一枚贝壳，严格来说它是这片海滩上最正当的居民之一——它本就属于这里。然而当人类将它捡起、把玩、带走、又丢弃时，它的身份便从"自然的一部分"变成了"人类活动的痕迹"。本所经过讨论，决定将其归入"神秘物品"：一枚贝壳，因人的介入，成了垃圾，这才是真正令人困惑之处。',
    weirdness: 6,
    frequency: 4,
    weight: 1,
    dangerLevel: 1,
    isPreset: true
  },
  {
    id: 'DMS-022',
    name: '锈迹斑斑的无名铁甲武士',
    latinName: 'Lamina ferrea ruginosa anonyma',
    category: '金属异物',
    discoveredAt: '大梅沙海滨公园沙滩',
    coordinates: '22°36\'04"N 114°18\'41"E',
    date: '2026-02-05',
    foundBy: '志愿者阿明',
    photoUrl: 'assets/hero-trash/铁皮.png',
    description: '一块形状不规则的生锈铁皮，边缘锋利，表面锈迹已呈橘红色，估计在海水与空气中已浸泡数年。本所对其来源进行了推断：船体残件、废弃设施、建筑垃圾……均有可能。铁皮在沙滩上具有真实的危险性，可能割伤赤脚行走的游客。本所特别提醒：此标本已采集，现场安全。',
    weirdness: 6,
    frequency: 3,
    weight: 8,
    dangerLevel: 3,
    isPreset: true
  },
  {
    id: 'DMS-023',
    name: '空框里装满了无限可能',
    latinName: 'Margo speculare vacuus infinitum',
    category: '日用生活',
    discoveredAt: '大梅沙海滨公园沙滩',
    coordinates: '22°36\'16"N 114°18\'53"E',
    date: '2025-10-10',
    foundBy: '志愿者小欣',
    photoUrl: 'assets/hero-trash/镜框.png',
    description: '一副没有镜片的眼镜框，或者一个相框，或者某种本所尚未命名的艺术装置。没有镜片，却仍保持着框架的形状，像一个失去内容的容器，或者一个等待填充的故事。本所有成员将其举起，透过空框望向大海，沉默了五秒钟。这五秒钟被计入了本次采集活动最有意义的时刻之一。',
    weirdness: 8,
    frequency: 2,
    weight: 3,
    dangerLevel: 1,
    isPreset: true
  },
  {
    id: 'DMS-024',
    name: '甲壳纲动物的跨界客串',
    latinName: 'Homarus marinus plasticae repatriatus',
    category: '神秘物品',
    discoveredAt: '大梅沙海滨公园沙滩',
    coordinates: '22°36\'18"N 114°18\'55"E',
    date: '2025-08-28',
    foundBy: '志愿者阿强',
    photoUrl: 'assets/hero-trash/龙虾.png',
    description: '一只龙虾造型的物件，出现在有真实龙虾生活过的海边，其象征意义令本所沉默良久。它是玩具？摆件？儿童读物的配套模型？本所无法确认。唯一确认的是，真正的龙虾从未主动来到沙滩上，而这只假龙虾，偏偏就在这里。本所为它举办了一场简单的"欢迎回家"仪式，随后将其收入档案。',
    weirdness: 9,
    frequency: 1,
    weight: 3,
    dangerLevel: 1,
    isPreset: true
  }
];

/* Merge preset + any supabase data (called by gallery.js) */
window.ALL_TRASH_DATA = [...window.PRESET_DATA];
